AllCops:
  TargetRubyVersion: 2.3

Metrics/MethodLength:
  Max: 200

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 220

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

# ruby 2.1, 2.2 support
Style/NumericPredicate:
  Enabled: false

Style/SafeNavigation:
  Enabled: false


# highly opinionated, subject to false positives, and likely to break valid code
Style/FormatStringToken:
  Enabled: false

# testing
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'test/**/*'
